export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_DISTANCE: "INVALID_DISTANCE",
  INVALID_CARGO_WEIGHT: "INVALID_CARGO_WEIGHT",
  UNSUPPORTED_VEHICLE_TYPE: "UNSUPPORTED_VEHICLE_TYPE",
  INVALID_EFFICIENCY_FACTOR: "INVALID_EFFICIENCY_FACTOR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
